# Generated by Django 4.1.5 on 2023-01-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
